services:

  db:
    image: mysql:8.4.1
    ports:
      - "3317:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=math_quiz
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passwd

volumes:
  db_data:
