services:
  api:
    image: amazoncorretto:21
    ports:
      - "8181:8080"
      - "5105:5005"
    volumes:
      - ./:/api:cached
    working_dir: /api
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.4.1
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=math_quiz
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passwd

volumes:
  db_data:
